//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shuttle.Core.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shuttle.Core.Data.DataResources", typeof(DataResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully opened connection string with name &apos;{0}&apos;..
        /// </summary>
        public static string ConnectionStringApproved {
            get {
                return ResourceManager.GetString("ConnectionStringApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required connection string with name &apos;{0}&apos; is not specified in the application configuration file..
        /// </summary>
        public static string ConnectionStringMissing {
            get {
                return ResourceManager.GetString("ConnectionStringMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new &apos;{0}&apos; QueryBuilder implementation could not be returned from the factory..
        /// </summary>
        public static string CouldNotCreateQueryBuilder {
            get {
                return ResourceManager.GetString("CouldNotCreateQueryBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create a connection for data source &apos;{0}&apos;..
        /// </summary>
        public static string CreateConnectionException {
            get {
                return ResourceManager.GetString("CreateConnectionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseConnection created for connection name &apos;{0}&apos;..
        /// </summary>
        public static string DatabaseConnectionCreated {
            get {
                return ResourceManager.GetString("DatabaseConnectionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbConnection created for connection name &apos;{0}&apos;..
        /// </summary>
        public static string DbConnectionCreated {
            get {
                return ResourceManager.GetString("DbConnectionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbConnection opened for connection name &apos;{0}&apos;..
        /// </summary>
        public static string DbConnectionOpened {
            get {
                return ResourceManager.GetString("DbConnectionOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbConnection open failed for connection name &apos;{0}&apos;: {1}.
        /// </summary>
        public static string DbConnectionOpenException {
            get {
                return ResourceManager.GetString("DbConnectionOpenException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbProviderFactory &apos;{0}&apos; has been cached..
        /// </summary>
        public static string DbProviderFactoryCached {
            get {
                return ResourceManager.GetString("DbProviderFactoryCached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query factory for query data identifier &apos;{0}&apos; has already been registered..
        /// </summary>
        public static string DuplicateQueryFactory {
            get {
                return ResourceManager.GetString("DuplicateQueryFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExistingDatabaseConnection returned for connection name &apos;{0}&apos;..
        /// </summary>
        public static string ExistingDatabaseConnectionReturned {
            get {
                return ResourceManager.GetString("ExistingDatabaseConnectionReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query factory &apos;{0}&apos; has not been registered..
        /// </summary>
        public static string MissingQueryFactory {
            get {
                return ResourceManager.GetString("MissingQueryFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to retrieve non-existent connection name &apos;{0}&apos; from ThreadStaticDatabaseConnectionCache..
        /// </summary>
        public static string ThreadStaticDatabaseConnectionCacheMissingEntry {
            get {
                return ResourceManager.GetString("ThreadStaticDatabaseConnectionCacheMissingEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified IQuery is not a QueryDefinition and does not implement IExecutableQuery.  The type of the given IQuery instance is &apos;{0}&apos;..
        /// </summary>
        public static string UnsupportedIQueryImplementation {
            get {
                return ResourceManager.GetString("UnsupportedIQueryImplementation", resourceCulture);
            }
        }
    }
}
