//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shuttle.Core.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shuttle.Core.Data.DataResources", typeof(DataResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not add a database context with a name of &apos;__current&apos; as that name is used to key the currently selected database context..
        /// </summary>
        public static string AddCurrentKeyDatabaseContextException {
            get {
                return ResourceManager.GetString("AddCurrentKeyDatabaseContextException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully opened connection string with name &apos;{0}&apos;..
        /// </summary>
        public static string ConnectionStringApproved {
            get {
                return ResourceManager.GetString("ConnectionStringApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbConnection open failed for connection string name &apos;{0}&apos;: {1}.
        /// </summary>
        public static string ConnectionStringApproveException {
            get {
                return ResourceManager.GetString("ConnectionStringApproveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [hidden].
        /// </summary>
        public static string ConnectionStringHiddenValue {
            get {
                return ResourceManager.GetString("ConnectionStringHiddenValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required connection string with name &apos;{0}&apos; is not specified in the application configuration file..
        /// </summary>
        public static string ConnectionStringMissing {
            get {
                return ResourceManager.GetString("ConnectionStringMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not current database context..
        /// </summary>
        public static string CurrentDatabaseContextNotFoundException {
            get {
                return ResourceManager.GetString("CurrentDatabaseContextNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to retrieve non-existent database context with connection string &apos;{0}&apos;..
        /// </summary>
        public static string DatabaseContextConnectionStringNotFoundException {
            get {
                return ResourceManager.GetString("DatabaseContextConnectionStringNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDatabaseContextFactory instance of type &apos;{0}&apos; has not been configured.  Cannot call &apos;Create()&apos; directly..
        /// </summary>
        public static string DatabaseContextFactoryNotConfiguredException {
            get {
                return ResourceManager.GetString("DatabaseContextFactoryNotConfiguredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to retrieve non-existent database context with key &apos;{0}&apos;..
        /// </summary>
        public static string DatabaseContextKeyNotFoundException {
            get {
                return ResourceManager.GetString("DatabaseContextKeyNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no active database context.  Use the database context factory to create a context..
        /// </summary>
        public static string DatabaseContextMissing {
            get {
                return ResourceManager.GetString("DatabaseContextMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to retrieve non-existent database context with name &apos;{0}&apos;..
        /// </summary>
        public static string DatabaseContextNameNotFoundException {
            get {
                return ResourceManager.GetString("DatabaseContextNameNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No `IDatabaseContextCache` implementation has been assigned to the `DatabaseContext`..
        /// </summary>
        public static string DatabaseContextStoreMissingException {
            get {
                return ResourceManager.GetString("DatabaseContextStoreMissingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbConnection open failed for database &apos;{0}&apos;: {1}.
        /// </summary>
        public static string DbConnectionOpenException {
            get {
                return ResourceManager.GetString("DbConnectionOpenException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create a connection from provider factory &apos;{0}&apos;..
        /// </summary>
        public static string DbProviderFactoryCreateConnectionException {
            get {
                return ResourceManager.GetString("DbProviderFactoryCreateConnectionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a database context with key &apos;{0}&apos; in the IDatabaseContextCache..
        /// </summary>
        public static string DuplicateDatabaseContextKeyException {
            get {
                return ResourceManager.GetString("DuplicateDatabaseContextKeyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query factory for query data identifier &apos;{0}&apos; has already been registered..
        /// </summary>
        public static string DuplicateQueryFactory {
            get {
                return ResourceManager.GetString("DuplicateQueryFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find embedded resource script for name &apos;{0}&apos; at path &apos;{1}&apos;..
        /// </summary>
        public static string EmbeddedScriptMissingException {
            get {
                return ResourceManager.GetString("EmbeddedScriptMissingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query factory &apos;{0}&apos; has not been registered..
        /// </summary>
        public static string MissingQueryFactory {
            get {
                return ResourceManager.GetString("MissingQueryFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IScriptProviderConfiguration instance returned null for the ResourceAssembly..
        /// </summary>
        public static string ResourceAssemblyMissingException {
            get {
                return ResourceManager.GetString("ResourceAssemblyMissingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory &apos;{0}&apos; was searched (recursively) for script file &apos;{1}&apos;.  Exactly 1 file must exist in the directory structure but {2} were found..
        /// </summary>
        public static string ScriptCountException {
            get {
                return ResourceManager.GetString("ScriptCountException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified IQuery is not a QueryDefinition and does not implement IExecutableQuery.  The type of the given IQuery instance is &apos;{0}&apos;..
        /// </summary>
        public static string UnsupportedIQueryImplementation {
            get {
                return ResourceManager.GetString("UnsupportedIQueryImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbConnection already open to database &apos;{0}&apos;..
        /// </summary>
        public static string VerboseDbConnectionAlreadyOpen {
            get {
                return ResourceManager.GetString("VerboseDbConnectionAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbConnection opened to database &apos;{0}&apos; on data source &apos;{1}&apos;..
        /// </summary>
        public static string VerboseDbConnectionCreated {
            get {
                return ResourceManager.GetString("VerboseDbConnectionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbConnection opened to database &apos;{0}&apos;..
        /// </summary>
        public static string VerboseDbConnectionOpened {
            get {
                return ResourceManager.GetString("VerboseDbConnectionOpened", resourceCulture);
            }
        }
    }
}
